package com.example.educapp.commons.classwork

import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.setValue
import androidx.lifecycle.ViewModel
import androidx.lifecycle.viewModelScope
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.launch
import kotlinx.serialization.KSerializer
import kotlinx.serialization.Serializable
import kotlinx.serialization.builtins.ListSerializer
import kotlinx.serialization.descriptors.PrimitiveKind
import kotlinx.serialization.descriptors.PrimitiveSerialDescriptor
import kotlinx.serialization.descriptors.SerialDescriptor
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder
import kotlinx.serialization.json.Json
import timber.log.Timber
import java.time.LocalDate
import java.time.LocalDateTime

// Status Tracking
enum class ClassworkStatus {
    DRAFT, APPROVED, ARCHIVED
}

// Main Partial Data Classes
@Serializable
data class ClassworkPartial(
    @Transient // Will be generated by Firestore
    val id: String = "",
    val groupId: String = "",
    val partialNumber: Int = 1,
    val title: String = "",
    val status: ClassworkStatus = ClassworkStatus.DRAFT,
    @Serializable(with = LocalDateSerializer::class)
    val createdDate: LocalDate = LocalDate.now(),
    @Serializable(with = LocalDateTimeSerializer::class)
    val lastModified: LocalDateTime = LocalDateTime.now()
)

@Serializable
data class ClassworkActivity(
    @Transient
    val id: String = "",
    @Transient
    val partialId: String = "",
    val title: String = "",
    val description: String = "",
    @Serializable
    val type: ActivityType = ActivityType.GRAMMAR_EXERCISE,
    @Serializable
    val status: ClassworkStatus = ClassworkStatus.DRAFT,
    @Serializable(with = LocalDateSerializer::class)
    val dueDate: LocalDate? = null,
    val aiGenerationContext: String = "",
    val materials: List<ClassworkMaterial> = emptyList()
) {
    @Serializable
    enum class ActivityType {
        ROLE_PLAY, GRAMMAR_EXERCISE, VOCABULARY_DRILL, READING_ASSIGNMENT
    }
}

@Serializable
data class ClassworkMaterial(
    @Transient
    val id: String = "",
    @Transient
    val activityId: String = "",
    @Serializable
    val type: MaterialType = MaterialType.TEXT,
    val content: String = "",
    val description: String = ""
) {
    @Serializable
    enum class MaterialType {
        PDF, IMAGE, TEXT, VIDEO, AUDIO, LINK
    }
}

@Serializable(with = LocalDateSerializer::class)
data class CustomDate(val date: LocalDate)

object LocalDateSerializer : KSerializer<LocalDate> {
    override val descriptor: SerialDescriptor =
        PrimitiveSerialDescriptor("LocalDate", PrimitiveKind.STRING)

    override fun serialize(encoder: Encoder, value: LocalDate) {
        encoder.encodeString(value.toString())
    }

    override fun deserialize(decoder: Decoder): LocalDate {
        return LocalDate.parse(decoder.decodeString())
    }
}

class LocalDateTimeSerializer : KSerializer<LocalDateTime> {
    override val descriptor = PrimitiveSerialDescriptor("LocalDateTime", PrimitiveKind.STRING)
    override fun serialize(encoder: Encoder, value: LocalDateTime) = encoder.encodeString(value.toString())
    override fun deserialize(decoder: Decoder) = LocalDateTime.parse(decoder.decodeString())
}

class ClassworkViewModel(
    private val repository: ClassworkRepository,
    val groupId: String
) : ViewModel() {

    private val _partials = MutableStateFlow<List<ClassworkPartial>>(emptyList())
    val partials: StateFlow<List<ClassworkPartial>> = _partials

    private val _activities = MutableStateFlow<List<ClassworkActivity>>(emptyList())
    val activities: StateFlow<List<ClassworkActivity>> = _activities

    private val _materials = MutableStateFlow<List<ClassworkMaterial>>(emptyList())
    val materials: StateFlow<List<ClassworkMaterial>> = _materials

    private val _uiState = MutableStateFlow<ClassworkUiState>(ClassworkUiState.Loading)
    val uiState: StateFlow<ClassworkUiState> = _uiState
    private val _previewActivities = MutableStateFlow<List<ClassworkActivity>>(emptyList())
    val previewActivities: StateFlow<List<ClassworkActivity>> = _previewActivities

    private val _currentPartial = MutableStateFlow<ClassworkPartial?>(null)
    val currentPartial: StateFlow<ClassworkPartial?> = _currentPartial

    var currentPartialId by mutableStateOf("")
        private set


    fun setCurrentPartial(partial: ClassworkPartial) {
        _currentPartial.value = partial
    }

    fun clearPreview() {
        _previewActivities.value = emptyList()
        _currentPartial.value = null
    }
    // Change the Success state to not require a message
    sealed interface ClassworkUiState {
        object Loading : ClassworkUiState
        object Success : ClassworkUiState  // Removed message parameter
        data class Error(val message: String) : ClassworkUiState
    }

    // Update loadAllClassworkData()

    init {
        loadAllClassworkData()
    }

    fun loadAllClassworkData() {
        _uiState.value = ClassworkUiState.Loading
        viewModelScope.launch {
            try {
                _partials.value = repository.getClassworkPartials(groupId)
                _uiState.value = ClassworkUiState.Success
            } catch (e: Exception) {
                _uiState.value = ClassworkUiState.Error("Failed to load data: ${e.message}")
            }
        }
    }

    fun approvePartial(partialId: String) {
        viewModelScope.launch {
            try {
                // Add this to your repository interface
                repository.updatePartialStatus(partialId, ClassworkStatus.APPROVED)
                _partials.value = _partials.value.map {
                    if (it.id == partialId) it.copy(status = ClassworkStatus.APPROVED) else it
                }
            } catch (e: Exception) {
                _uiState.value = ClassworkUiState.Error("Approval failed: ${e.message}")
            }
        }
    }
    fun getPartialById(partialId: String): ClassworkPartial? {
        return _partials.value.find { it.id == partialId }
    }

    fun approveActivity(activityId: String) {
        viewModelScope.launch {
            try {
                repository.updateActivityStatus(activityId, ClassworkStatus.APPROVED)
                _activities.value = _activities.value.map {
                    if (it.id == activityId) it.copy(status = ClassworkStatus.APPROVED) else it
                }
            } catch (e: Exception) {
                _uiState.value = ClassworkUiState.Error("Approval failed: ${e.message}")
            }
        }
    }

    fun createNewPartial(partial: ClassworkPartial) {
        viewModelScope.launch {
            try {
                repository.createClassworkPartial(partial)
                loadAllClassworkData()
            } catch (e: Exception) {
                _uiState.value = ClassworkUiState.Error("Creation failed: ${e.message}")
            }
        }
    }

    // Update processAiResponse in ClassworkViewModel
    fun processAiResponse(partialId: String, aiResponse: String) {
        viewModelScope.launch {
            _uiState.value = ClassworkUiState.Loading
            try {
                val parsed = parseAiResponse(aiResponse)
                _previewActivities.value = parsed
                _uiState.value = ClassworkUiState.Success
            } catch (e: Exception) {
                _uiState.value = ClassworkUiState.Error("AI Processing failed: ${e.message}")
            }
        }
    }

    fun confirmAndSaveActivities() {
        viewModelScope.launch {
            val partialId = currentPartial.value?.id ?: return@launch
            _uiState.value = ClassworkUiState.Loading

            try {
                // Save activities
                repository.saveActivities(partialId, _previewActivities.value)

                // Save materials
                _previewActivities.value.forEach { activity ->
                    repository.saveMaterials(activity.id, activity.materials)
                }

                loadAllClassworkData()
                clearPreview()
                _uiState.value = ClassworkUiState.Success
            } catch (e: Exception) {
                _uiState.value = ClassworkUiState.Error("Save failed: ${e.message}")
            }
        }
    }

    private fun extractJsonFromResponse(response: String): String {
        val jsonStart = response.indexOfFirst { it == '[' }
        val jsonEnd = response.indexOfLast { it == ']' }
        return if (jsonStart != -1 && jsonEnd != -1) {
            response.substring(jsonStart..jsonEnd)
        } else {
            ""
        }
    }

    internal fun parseAiResponse(response: String): List<ClassworkActivity> {
        return try {
            Json.decodeFromString(
                deserializer = ListSerializer(ClassworkActivity.serializer()),
                string = response
            )
        } catch (e: Exception) {
            Timber.e(e, "Failed to parse AI response")
            emptyList()
        }
    }
}